---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cni
  namespace: istio-system
  annotations:
    meta.helm.sh/release-name: cni
    meta.helm.sh/release-namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  interval: 5m
  chart:
    spec:
      chart: cni
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
