apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-security-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/security/cert-manager/app
  dependsOn:
    - name: cluster-apps-networking-gateway-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
  wait: true