---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium/ks.yaml
  - ./cloudflared/ks.yaml
  - ./coredns/ks.yaml
  - ./external-dns/ks.yaml
  - ./gateway-api/ks.yaml
  - ./headscale/ks.yaml
  - ./istio-system
  - ./unifi-controller/ks.yaml
