apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vault-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - vers=4.1
  nfs:
    path: /mnt/primary-pool/K8s/vault/data-vault-0
    server: 10.0.6.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-0
  namespace: vault
spec:
  storageClassName: ""
  volumeName: data-vault-0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vault-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - vers=4.1
  nfs:
    path: /mnt/primary-pool/K8s/vault/data-vault-1
    server: 10.0.6.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-1
  namespace: vault
spec:
  storageClassName: ""
  volumeName: data-vault-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vault-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - vers=4.1
  nfs:
    path: /mnt/primary-pool/K8s/vault/data-vault-2
    server: 10.0.6.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-2
  namespace: vault
spec:
  storageClassName: ""
  volumeName: data-vault-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
