---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: operator
      version: 5.0.9
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
