---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-gateway-api
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/gateway-api/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: CustomResourceDefinition
      name: gateway.networking.k8s.io
