apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-1
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 2
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: external-dns-1
    provider: rfc2136
    env:
      - name: EXTERNAL_DNS_RFC2136_HOST
        value: "10.0.0.3"
      - name: EXTERNAL_DNS_RFC2136_PORT
        value: "53"
      - name: EXTERNAL_DNS_RFC2136_ZONE
        value: akchristiansen.com
      - name: EXTERNAL_DNS_RFC2136_TSIG_AXFR
        value: "true"
      - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
        value: externaldns-key
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
        valueFrom:
          secretKeyRef:
            name: bind-secret
            key: rndc-algorithm
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: bind-secret
            key: rndc-secret
    policy: sync
    sources:
      - service
      - gateway-httproute
      - gateway-tcproute
      # - gateway-tlsroute
    txtOwnerId: default
    txtPrefix: k8s.
    serviceMonitor:
      enabled: false
