apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: flux-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
  data:
    - secretKey: secret_key
      remoteRef:
        key: authentik-secrets
        property: secret_key
    - secretKey: postgresql_key
      remoteRef:
        key: authentik-secrets
        property: postgresql_key
    - secretKey: geoip_accountid
      remoteRef:
        key: authentik-secrets
        property: geoip_accountid
    - secretKey: geoip_licensekey
      remoteRef:
        key: authentik-secrets
        property: geoip_licensekey
    - secretKey: from_email
      remoteRef:
        key: authentik-secrets
        property: from_email
    - secretKey: email_host
      remoteRef:
        key: authentik-secrets
        property: email_host
