---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-cloudflared
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/cloudflared/app
  dependsOn:
    - name: cluster-apps-security-external-secrets-stores
    - name: cluster-apps-networking-istio-system-istiod
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cloudflared
      namespace: cloudflared
