---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-media-nextcloud
  namespace: flux-system
spec:
  path: ./cluster/apps/media/nextcloud/app
  dependsOn:
    - name: cluster-apps-networking-istio-system-istiod
    - name: cluster-apps-database-cloudnative-pg-cluster
    - name: cluster-apps-database-redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: nextcloud
      namespace: nextcloud
  interval: 30m
  retryInterval: 1m
  timeout: 5m
