---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: immich
data:
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: verbose
  NODE_ENV: "production"
  REDIS_HOSTNAME: redis-master.redis.svc.cluster.local
  REDIS_PORT: "6379"
  IMMICH_SERVER_URL: http://immich-server.immich.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.immich.svc.cluster.local:3003
  MACHINE_LEARNING_CACHE_FOLDER: /cache
  TRANSFORMERS_CACHE: /usr/src/app/.transformers_cache
  PUBLIC_IMMICH_SERVER_URL: https://photos.akchristiansen.com
  IMMICH_API_URL_EXTERNAL: /api
  DB_VECTOR_EXTENSION: pgvector
