---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
  namespace: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_DATABASE_NAME: immich
        DB_PORT: "5432"
        DB_HOSTNAME: postgres-rw.cloudnative-pg.svc.cluster.local
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DB_USERNAME: immich
  dataFrom:
    - extract:
        key: immich-secrets
