---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./gateway.yaml
  - ./namespace.yaml
  - ./network-policy.yaml
  - ./nfs-pvc.yaml
  - ./server
  - ./microservices
  - ./machine-learning
labels:
  - pairs:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
      app.kubernetes.io/part-of: immich
