apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
  namespace: cloudflared
data:
  config.yaml: |
    ---
    originRequest:
      http2Origin: true

    ingress:
      - hostname: akchristiansen.com
        service: https://external-gateway-istio.istio-system.svc.cluster.local
        originRequest:
          originServerName: external.akchristiansen.com
      - hostname: "*.akchristiansen.com"
        service: https://external-gateway-istio.istio-system.svc.cluster.local
        originRequest:
          originServerName: external.akchristiansen.com
      - service: http_status:404
