---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: cloudflared-tunnel-secret
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .CLOUDFLARE_ACCOUNT_TAG }}",
            "TunnelSecret": "{{ .CLOUDFLARE_TUNNEL_SECRET }}",
            "TunnelID": "{{ .CLUSTER_CLOUDFLARE_TUNNEL_ID }}"
          }
  data:
    - secretKey: CLOUDFLARE_ACCOUNT_TAG
      remoteRef:
        key: cloudflared-tunnel-secrets
        property: CLOUDFLARE_ACCOUNT_TAG
    - secretKey: CLOUDFLARE_TUNNEL_SECRET
      remoteRef:
        key: cloudflared-tunnel-secrets
        property: CLOUDFLARE_TUNNEL_SECRET
    - secretKey: CLUSTER_CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: cloudflared-tunnel-secrets
        property: CLUSTER_CLOUDFLARE_TUNNEL_ID
