---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-minio
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/minio/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: minio
      namespace: minio
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-minio-tenant
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/minio/tenant
  prune: true
  dependsOn:
  - name: cluster-apps-storage-minio
  - name: cluster-apps-networking-istio-system-istiod
  - name: cluster-apps-security-cert-manager
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: k8s-pool-0
      namespace: minio-tenant
  interval: 30m
  retryInterval: 1m
  timeout: 10m