---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-csi
  namespace: kube-system
  annotations:
    meta.helm.sh/release-name: nfs-csi
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"
    storageClasses:
    - name: nfs-csi
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
      mountOptions:
      - noatime
      - nfsvers=4
    volumeSnapshotClasses:
    - name: nfs-csi
      deletionPolicy: Delete
      annotations:
        k10.kasten.io/is-snapshot-class: "true"
      parameters:
        detachedSnapshots: "false"
    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          protocol: https
          host: nas-1.akchristiansen.com
          port: 443
          apiKey: 1-Y06aWHZATBMTZQcuu7PsJ69bagdzfp75rxsGU1fXYedws0iHP8f758Zrrq9lBl32
          allowInsecure: true
        zfs:
          datasetParentName: primary-pool/K8s/nfs
          detachedSnapshotsDatasetParentName: primary-pool/K8s/nfs-snapshots
          datasetEnableQuotas: false
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          #shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          shareHost: 10.0.6.2
          shareAlldirs: false
          shareAllowedNetworks:
          - 10.0.3.0/24
          shareMaprootUser: root
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""