---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-media-jellyfin
  namespace: flux-system
spec:
  path: ./cluster/apps/media/jellyfin/app
  dependsOn:
    - name: cluster-apps-networking-istio-system-istiod
    - name: cluster-apps-storage-nfs-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-git-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: jellyfin
      namespace: jellyfin
  interval: 30m
  retryInterval: 1m
  timeout: 3m
