---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-utilities-reloader
  namespace: flux-system
spec:
  path: ./cluster/apps/utilities/reloader/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-git-repo
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: reloader-reloader
      namespace: reloader
  interval: 30m
  retryInterval: 1m
  timeout: 3m