---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-cni
  namespace: linkerd
spec:
  interval: 15m
  chart:
    spec:
      chart: linkerd2-cni
      version: 30.11.0
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false