apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k10-dr-secret
  namespace: kasten-io
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: k10-dr-secret
  data:
    - secretKey: key
      remoteRef:
        key: k10-secrets
        property: dr_key
    - secretKey: source
      remoteRef:
        key: k10-secrets
        property: dr_source
    - secretKey: vault-kv-version
      remoteRef:
        key: k10-secrets
        property: dr_vault-kv-version
    - secretKey: vault-mount-path
      remoteRef:
        key: k10-secrets
        property: dr_vault-mount-path
    - secretKey: vault-secret-path
      remoteRef:
        key: k10-secrets
        property: dr_vault-secret-path
