---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: https
  namespace: kasten-io
spec:
  parentRefs:
    - name: internal-gateway
      namespace: istio-system
      sectionName: https
  hostnames: ["k10.akchristiansen.com"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gateway
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
  namespace: kasten-io
spec:
  parentRefs:
    - name: internal-gateway
      namespace: istio-system
      sectionName: http
  hostnames: ["k10.akchristiansen.com"]
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
