---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 6.5.4
      sourceRef:
        kind: HelmRepository
        name: kasten-io
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: helm-values
