---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 6.5.0
      sourceRef:
        kind: HelmRepository
        name: kasten-io
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    networkPolicy:
      create: true
    global:
      persistence:
        mountPath: "/mnt/k10state"
        enabled: true
        storageClass: "nfs-csi"
        accessMode: ReadWriteOnce
        size: 20Gi
    eula:
      accept: true
      company: "No Company"
      email: "gage@gageserver.com"
    auth:
      tokenAuth:
        enabled: true
    cacertconfigmap:
      name: "custom-ca-bundle-store"
    encryption:
      primaryKey:
        vaultTransitKeyName: "k10-transit-key"
        vaultTransitPath: "k10-transit"
    vault:
      role: "k10-transit"
      address: "https://vault-active.vault.svc.cluster.local:8200"
    prometheus:
      server:
        enabled: false
    grafana:
      enabled: false
    injectKanisterSidecar:
      enabled: true
      namespaceSelector:
        matchLabels:
          k10/injectKanisterSidecar: "true"
      webhookServer:
        port: 9784
