---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-authentik-to-cloudnative-pg"
  namespace: cloudnative-pg
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/cluster: postgres
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: authentik
            app.kubernetes.io/name: authentik
      toPorts:
        - ports:
            - port: '5432'
              protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-cluster-to-cloudnative-pg-webhook"
  namespace: cloudnative-pg
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: '9443'
              protocol: TCP
            - port: '443'
              protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-postgres-to-postgres"
  namespace: cloudnative-pg
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/cluster: postgres
  ingress:
    - fromEndpoints:
        - matchLabels:
            cnpg.io/cluster: postgres
      toPorts:
        - ports:
            - port: '5432'
              protocol: TCP
