---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-linkerd-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/linkerd/crds/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-git-repo
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: linkerd-crds
      namespace: linkerd