apiVersion: v1
kind: Service
metadata:
  name: ark
  namespace: ark
  annotations:
    io.cilium/lb-ipam-ips: 10.0.0.5
spec:
  ports:
    - name: rcon
      protocol: TCP
      port: 32330
      targetPort: 32330
    - name: gameudp
      protocol: UDP
      port: 7777
      targetPort: 7777
    - name: gameudp2
      protocol: UDP
      port: 7778
      targetPort: 7778
    - name: queryudp
      protocol: UDP
      port: 27015
      targetPort: 27015
  selector:
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark-cluster
  type: LoadBalancer
