---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-cilium
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/cilium/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cilium
      namespace: kube-system