apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-secrets
  namespace: velero
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: velero-secrets
  data:
    - secretKey: cloud
      remoteRef:
        key: velero-secrets
        property: cloud
