---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-database-redis
  namespace: flux-system
spec:
  path: ./cluster/apps/database/redis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m