apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-coredns
  namespace: flux-system
spec:
  path: ./cluster/apps/networking/coredns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-coredns-k8s-gateway
  namespace: flux-system
spec:
  path: ./cluster/apps/networking/coredns/k8s-gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: k8s-gateway
      namespace: kube-system
