---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-istio-system-base
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/istio-system/base/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: base
      namespace: istio-system
  wait: true
