---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-bind9
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/bind9/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: bind9-0
      namespace: bind9
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: bind9-1
      namespace: bind9
