---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-controller
  namespace: unifi-controller
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      main:
        containers:
          main:
            dependsOn:
              - mongodb
            image:
              repository: lscr.io/linuxserver/unifi-network-application
              tag: 8.0.26
              pullPolicy: IfNotPresent
            env:
              PUID: 1000
              PGID: 1000
              TZ: America/Anchorage
              MONGO_HOST: localhost
              MONGO_PORT: 27017
              MONGO_DBNAME: unifi
              MEM_LIMIT: 1024
              MEM_STARTUP: 1024
            envFrom:
              - secretRef:
                  name: unifi-secrets
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8443
                  initialDelaySeconds: 30
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 20
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 1
                memory: 1500Mi
          mongodb:
            image:
              repository: mongo
              tag: 4.4.27
              pullPolicy: IfNotPresent
            probes:
              liveness: &mongoprobes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 27017
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 20
              readiness: *mongoprobes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 500m
                memory: 500Mi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              fsGroupChangePolicy: "OnRootMismatch"
        initContainers:
          unifi-ssl:
            image:
              repository: lscr.io/linuxserver/unifi-network-application
              tag: 8.0.26
              pullPolicy: IfNotPresent
            command:
              [
                "sh",
                "-c",
                "mkdir -p /config/data /config/logs && rm -f /config/data/keystore && keytool -import -alias ca -file /usr/lib/unifi/tls/ca.crt -keystore /config/data/keystore -storepass aircontrolenterprise -noprompt && openssl pkcs12 -export -in /usr/lib/unifi/tls/tls.crt -inkey /usr/lib/unifi/tls/tls.key -out /tmp/unifi.p12 -name unifi -passout pass:aircontrolenterprise && keytool -importkeystore -srckeystore /tmp/unifi.p12 -srcstoretype PKCS12 -srcstorepass aircontrolenterprise -destkeystore /config/data/keystore -deststorepass aircontrolenterprise -noprompt && rm /tmp/unifi.p12",
              ]
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: false
            port: 0
          https-admin:
            enabled: true
            port: 8443
            protocol: TCP
          http-guest:
            enabled: true
            port: 8880
            protocol: TCP
          https-guest:
            enabled: true
            port: 8843
            protocol: TCP
          com:
            enabled: true
            port: 8080
            protocol: TCP
      mongodb:
        enabled: true
        primary: false
        controller: main
        ports:
          http:
            enabled: false
            port: 0
          mongodb:
            enabled: true
            port: 27017
            protocol: TCP
    persistence:
      unifi-data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: unifi-controller-unifi
        advancedMounts:
          main:
            main:
              - path: /config
                readOnly: false
            unifi-ssl:
              - path: /config
                readOnly: false
      mongodb-data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: unifi-controller-mongodb
        advancedMounts:
          main:
            mongodb:
              - path: /data/db
                readOnly: false
      mongodb-init:
        type: secret
        name: mongo-init-script
        advancedMounts:
          main:
            mongodb:
              - path: /docker-entrypoint-initdb.d/mongo-init-script.js
                readOnly: true
                subPath: MONGO_INIT_SCRIPT
      tls-secrets:
        type: secret
        name: tls-secrets
        advancedMounts:
          main:
            unifi-ssl:
              - path: /usr/lib/unifi/tls/tls.crt
                readOnly: true
                subPath: tls.crt
              - path: /usr/lib/unifi/tls/tls.key
                readOnly: true
                subPath: tls.key
              - path: /usr/lib/unifi/tls/ca.crt
                readOnly: true
                subPath: ca.crt
