apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-controller-unifi
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - vers=4.1
  nfs:
    path: /mnt/primary-pool/K8s/nfs/unifi-controller-unifi
    server: 10.0.3.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-unifi
  namespace: unifi-controller
spec:
  storageClassName: ""
  volumeName: unifi-controller-unifi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-controller-mongodb
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - vers=4.1
  nfs:
    path: /mnt/primary-pool/K8s/nfs/unifi-controller-mongodb
    server: 10.0.3.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-mongodb
  namespace: unifi-controller
spec:
  storageClassName: ""
  volumeName: unifi-controller-mongodb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi