---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-akchristiansen-com
  namespace: unifi-controller
spec:
  secretName: unifi-akchristiansen-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: unifi.akchristiansen.com
  dnsNames:
    - unifi.akchristiansen.com
