apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-security-authentik-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/security/authentik/secrets
  dependsOn:
    - name: cluster-apps-security-external-secrets-stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-security-authentik
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/security/authentik/app
  dependsOn:
    - name: cluster-apps-security-authentik-secrets
    - name: cluster-apps-networking-istio-system-istiod
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: authentik
      namespace: authentik
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: authentik-secrets
        optional: false