---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-security-authentik
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/security/authentik/app
  dependsOn:
    - name: flux-variables
    - name: cluster-apps-networking-istio-system-istiod
    - name: cluster-apps-networking-istio-system-gateways-external
    - name: cluster-apps-database-cloudnative-pg-cluster
    - name: cluster-apps-database-redis
    - name: cluster-apps-storage-csi-nfs
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: authentik
      namespace: authentik
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: authentik-secrets
        optional: false
