---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-istio-system-issuers
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/istio-system/issuers/app
  dependsOn:
    - name: cluster-apps-security-cert-manager
    - name: cluster-apps-security-vault
    - name: flux-variables
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: flux-issuer-secrets
        optional: false
      - kind: Secret
        name: ca-bundle
        optional: false
