---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-external-dns
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/external-dns/app
  dependsOn:
    - name: cluster-apps-security-external-secrets-stores
    - name: cluster-apps-networking-istio-system-istiod
    - name: cluster-apps-networking-gateway-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: external-dns
      namespace: external-dns
