---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: akchristiansen-com
  namespace: istio-system
spec:
  secretName: akchristiansen-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: akchristiansen.com
  dnsNames:
    - akchristiansen.com
    - "*.akchristiansen.com"
