apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ingress-issuer
spec:
  vault:
    path: pki/sign/ingress-role
    server: https://vault-active.vault.svc.cluster.local:8200
    caBundle: ${ca_bundle_base64}
    auth:
      appRole:
        path: approle
        roleId: ${ingress_issuer_roleid}
        secretRef:
          name: ingress-issuer-approle
          key: secretId