apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: istio-issuer
spec:
  vault:
    path: pki/sign/istio-role
    server: https://vault-active.vault.svc.cluster.local:8200
    caBundle: ${ca_bundle_base64}
    auth:
      appRole:
        path: approle
        roleId: "${istio_issuer_roleid}"
        secretRef:
          name: istio-issuer-approle
          key: secretId
