---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: istio-issuer-approle
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: istio-issuer-approle
  data:
    - secretKey: secretId
      remoteRef:
        key: issuer-secrets
        property: istio-issuer-secretid
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ingress-issuer-approle
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: ingress-issuer-approle
  data:
    - secretKey: secretId
      remoteRef:
        key: issuer-secrets
        property: ingress-issuer-secretid
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: cloudflare-secret
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: issuer-secrets
        property: CLOUDFLARE_API_TOKEN
