apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-networking-bind9
    - name: cluster-apps-networking-gateway-api
  path: ./cluster/apps/networking/external-dns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
