apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dc1-pvc
  namespace: windows-vms
spec:
  storageClassName: "iscsi-csi"
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
