---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-snapshot-controller
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/snapshot-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: snapshot-controller
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m