apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: authentik-gateway
  namespace: authentik
  annotations:
    io.cilium/lb-ipam-ips: 10.0.0.4
    cert-manager.io/cluster-issuer: ingress-issuer
spec:
  gatewayClassName: istio
  listeners:
  - name: https
    hostname: auth.akchristiansen.com
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: tls-secrets
    allowedRoutes:
      namespaces:
        from: Same
  - name: http
    hostname: auth.akchristiansen.com
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: https
  namespace: authentik
spec:
  parentRefs:
  - name: authentik-gateway
    sectionName: https
  hostnames: ["auth.akchristiansen.com"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: authentik
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
  namespace: authentik
spec:
  parentRefs:
  - name: authentik-gateway
    sectionName: http
  hostnames: ["auth.akchristiansen.com"]
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301