---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2024.2.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    server:
      replicas: 2
      pdb:
        enabled: true
    worker:
      replicas: 2
      pdb:
        enabled: true
    authentik:
      secret_key: ${secret_key}
      email:
        host: ${email_host}
        port: 25
        from: ${from_email}
      postgresql:
        host: "postgres-rw.cloudnative-pg.svc.cluster.local"
        name: "authentik"
        user: "authentik"
        password: ${postgresql_key}
        port: 5432
      redis:
        host: "redis-master.redis.svc.cluster.local"
