---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-gateway-to-authentik"
  namespace: authentik
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: authentik
  ingress:
    - fromEndpoints:
        - matchLabels:
            istio.io/gateway-name: external-gateway
            k8s:io.kubernetes.pod.namespace: istio-system
      toPorts:
        - ports:
            - port: '80'
              protocol: TCP
            - port: '9000'
              protocol: TCP
