---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  interval: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
  uninstall:
    keepHistory: false
  values:
    runtimeClassName: nvidia
