---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: external-gateway
  namespace: istio-system
  annotations:
    lbipam.cilium.io/ips: 10.0.0.4
    lbipam.cilium.io/sharing-key: 'external-gateway'
    lbipam.cilium.io/sharing-cross-namespace: istio-system,headscale
    external-dns.alpha.kubernetes.io/target: "216.137.248.246"
  labels:
    gateway: external
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: akchristiansen-com-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: external-gateway
  namespace: istio-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: external-gateway-istio
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-gateway
  namespace: istio-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      istio.io/gateway-name: external-gateway
