---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-database-mariadb
  namespace: flux-system
spec:
  path: ./cluster/apps/database/mariadb/app
  prune: true
  dependsOn:
    - name: cluster-apps-storage-csi-iscsi
    - name: cluster-apps-networking-istio-system-istiod
    - name: cluster-apps-security-external-secrets-stores
  sourceRef:
    kind: GitRepository
    name: github
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
