---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
  uninstall:
    keepHistory: false
  values:
    controller:
      type: deployment
    image:
      repository: jellyfin/jellyfin
      tag: latest
    env:
      TZ: America/Anchorage
    service:
      main:
        ports:
          http:
            port: 8096
            enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "tv.apps.akchristiansen.com"
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - hosts:
        #       - *host
        #     insecureEdgeTerminationPolicy: Redirect
        #     termination: edge
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 100Gi
        mountPath: /config
      cache:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 100Gi
        mountPath: /cache
      media:
        enabled: false
        type: pvc
        accessMode: ReadWriteOnce
        size: 100Gi
        mountPath: /media
    resources:
      requests:
        cpu: 500m
        memory: 500Mi