---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4.1
  nfs:
    path: /mnt/qsan-storage/media-data
    server: 10.0.6.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: tv
spec:
  storageClassName: ""
  volumeName: media-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
