---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-git-repo
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://git@nas-1.akchristiansen.com:2222/gage/temp.git
  ref:
    branch: main
  secretRef:
    name: flux-git-repo
  ignore: |
    # exclude all
    /*
    # include cluster directory
    !/cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-git-repo