---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: github
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://git@github.com:Cubea01/gitops.git
  ref:
    branch: main
  secretRef:
    name: github
  ignore: |
    # exclude all
    /*
    # include cluster directory
    !/cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: github