---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs
  namespace: csi
spec:
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: nfs-driver
      optional: false
