apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=kubernetes-sigs/gateway-api
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.8.0/experimental-install.yaml
  - ./network-policy.yaml
patchesStrategicMerge:
  - ./namespace.yaml
