---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: external-dns-cloudflare-secret
  data:
    - secretKey: CF_API_EMAIL
      remoteRef:
        key: external-dns-secrets
        property: CF_API_EMAIL
    - secretKey: CF_API_KEY
      remoteRef:
        key: external-dns-secrets
        property: CF_API_KEY
