---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iscsi-csi
  namespace: kube-system
  annotations:
    meta.helm.sh/release-name: iscsi-csi
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    node:
      mount:
        checkFilesystem:
          ext4:
            enabled: true
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
    csiDriver:
      name: "org.democratic-csi.iscsi"
    storageClasses:
    - name: iscsi-csi
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      # annotations:
      #   k10.kasten.io/forcegenericbackup: "true"
      parameters:
        fsType: ext4
      secrets:
        node-stage-secret:
          node-db.node.session.auth.authmethod: CHAP
          node-db.node.session.auth.username: kubernetes
          node-db.node.session.auth.password: 2#Mr*!9&$Ya*5F
    volumeSnapshotClasses:
    - name: iscsi-csi
      deletionPolicy: Delete
      annotations:
        k10.kasten.io/is-snapshot-class: "true"
      parameters:
        detachedSnapshots: "false"
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id:
        httpConnection:
          protocol: https
          host: nas-1.akchristiansen.com
          port: 443
          apiKey: 1-Y06aWHZATBMTZQcuu7PsJ69bagdzfp75rxsGU1fXYedws0iHP8f758Zrrq9lBl32
          allowInsecure: true
        zfs:
          datasetParentName: primary-pool/K8s/iscsi
          detachedSnapshotsDatasetParentName: primary-pool/K8s/iscsi-snapshots
          zvolCompression: ""
          zvolDedup: ""
          zvolEnableReservation: false
          zvolBlocksize: 16K
        iscsi:
          targetPortal: "10.0.3.2:3260"
          targetPortals: []
          interface:
          nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          targetGroups:
            - targetGroupPortalGroup: 5
              targetGroupInitiatorGroup: 10
              targetGroupAuthType: None
              targetGroupAuthGroup:
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: "SSD"
          extentAvailThreshold: 0