apiVersion: v1
kind: Secret
metadata:
    name: unseal-token
    namespace: vault
stringData:
    unseal-token: ENC[AES256_GCM,data:8NmkYPZtqRRqg4oGmal97cZKWdMMGRveWynnNqLMRi5Xp6xhZSn2J9oMd3zG1+wM8R/hIuS5WsScCmm7FAY29c5is96Jphx0/MyUBWVa20rsF8Phhz2zVRf+UWaD5V4=,iv:ZCwcO7JlrcauU2E5TObckRwJlcyWqfrWxwXMg30GY8w=,tag:yvZH8kcnylhiWkVWZQzkrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://pi-vault.akchristiansen.com:8200
          engine_path: sops
          key_name: vault-key
          created_at: "2023-10-22T23:01:41Z"
          enc: vault:v1:Q3eV3bu61PBh3/ahwZSbL35su6sTNX4BlPIu1fnCdbLD9CWJe9XIUzaib2dMhKpl2PdeilXN1i0HH5F4A+6Ft5YfiHZFAwpRGH4uMgiajraUUxeeSUE+1hEC7//mRgSw76xiZoeyRcuMhRG4f19wSObnCXd6c3+Ju+WFrCMw0mV/ksTKopuJdyJW4B3yyrVosMYWdlYyUCwxKCJ+LlmHxYjlfNry+ce7V0dqzZthuzQxQUQ5RCUulKzMMfsNl+Vf5BeeG44jswG7uojJqh8NJN4RIo9q0lci10ss9FVugKM4FF4KY7PICcVoTh25ydgak9kB9h3bXcY08ies09qRDQPzfX9crc9No623mPkXBKpxfRFDXNKgzBWGMnkIkaNsHwQAGcu3so9EWZIAUq6XA1L+JZlKstLwkP/4/oOWEce0S4bzVCgvB7W9eayQSF7a65ui0WkG0FUlD+6rlIqdxvylwVVBZNJF2qFrWInXePaoqWulx7ffcSsNkKp5AhykYF6u3GaKqfxfW6wkHYdhwpUzLtWfn81fRGwYCCkfdYosyomRoWTXLooilo83VEhjs1mUDK6A3t9ofbzgY2xtFi6i7DQH0UdmhWH/VbPrc/KBxD+LT9UtqUPibJPV3R4jboxOq/8rnn965Re3hGkImHaZ2Ad+X3ydqozI+aR1t3M=
    age: []
    lastmodified: "2023-10-22T23:01:47Z"
    mac: ENC[AES256_GCM,data:1G8iecOaQ306272cPxLotlkBL/mmZXw8XteqPAHGzH2TYr41TySPWGUUVyXbBWegfzjZHgY2e821GGQI2zqDxdG3uSsYaZOamK8tvxDiFcsFQWm9VVQMCE2YEYgAOdQU90zu0gCer7nzYi6VsYi4Bp8BQ8Dxk2ZLhEY59X1KN6Y=,iv:aRZ4fKn0rKHkToIZdkFYq7C3cXblbjUKmtnveWW2NW4=,tag:KIPJVNrq2TXEmOdzine+iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
