apiVersion: v1
kind: Secret
metadata:
    name: unseal-token
    namespace: vault
stringData:
    unseal-token: ENC[AES256_GCM,data:nHpjKMjNod7mSEHW5NECHpS9chUaKAQRR7oSnBiq/Ggd7v0rWSTW9aZFFh9SbLl4vcKLsaVj/89RaqLkoWUfiK96bP6u0taFgI3QUR25V6sTBajeG7YKZ1owtTN6RBE=,iv:bwC/nc6QNxmL95BOqTBiUEBfqC6got1a0BOvM3e76ng=,tag:dIMthRwJufwVNpYuXqKvpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://pi-vault.akchristiansen.com:8200
          engine_path: sops
          key_name: vault-key
          created_at: "2023-10-22T22:37:24Z"
          enc: vault:v1:NI0c3Kmn/x+SykKizm5TtuanXcIaT+NAQ61/QkFk1Jk6YDpT6GPCH6nXXy9dL6xFY7/9PBa3SXMPP75DRhvYXt97n7wMt7B98Py4ELAmiHRHmiSwryVG2vk6eqzCfKJ57d6yfmW37ZsdqUmh1qe7PHQ8xcdf8PmzgEfv5FrwQW4PNOhBJVJLiogex3aWmHNAlcJd5XiafqegZCbPm2rMg5TzYqsfU4rfYczB7zHKTKq20IxwASougSFPgmSGh+s3Mm9xHmQk82fuHkVdCnyZ2HiQYkimlYXX6s+sDeV82gQtxoG1XRuPibZoL5U32ppmgrr5MdlTJc1mYge17DVsm2fo5OUuyC0pYks07/2AgGii97yJwVHS11MNIPHAQlfg4YKh1b2peYdCEbhGDY1LomdVDwkvQWJEHm9iH653OI1SCjRa6rvtZ660lZ5J00xY4dPjwoZWhe7ZxBez4F7JLWNda+KkjYWwSDO0a8DbB1rsU1fho/wRm7ah4/PZdgDhITzk15TpeJ4GIcWbAv9/o6jDsZ49EAwgQ2dDnhmYmiTrSzF9EDWlkhky1x/1CHzzH4J78R6UwAFBt6jQSYa5gQXWLJ0e4h73rseeEIewQAQtEsTGnTq/XiDuBLSIXlAAV4nB2+fGpTbpiq0AxA8caK3tyd+FSvmNdBkEorBRUVI=
    age: []
    lastmodified: "2023-10-22T22:37:24Z"
    mac: ENC[AES256_GCM,data:11qCoTLC64Nh/c6j5tvK7eUYXD5L+azgGSkH/CWQxkL6cp9yUMm2QYv4guQyEBTFSqrBGMOK9lsOxIhds22MVP6W/mkewMmnJTkX9jdjXc/xcw5ptJzVU0Z3/z4UFEpjkMoNwjLk4JSyfa/rLXGHVxautRZCAqACATT4c8QQlIY=,iv:3AHbtZsSln2Fv+qpurbF0kSuLuch8EJ4b0aT7cfntLA=,tag:LXGDWwl+xcadQenRj9LaJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
