apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
  namespace: vault
spec:
  secretName: tls-secrets
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: vault.akchristiansen.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - vault.akchristiansen.com
    - vault.vault.svc.cluster.local
    - vault-active.vault.svc.cluster.local
    - vault-0.vault-internal.vault.svc.cluster.local
    - vault-1.vault-internal.vault.svc.cluster.local
    - vault-2.vault-internal.vault.svc.cluster.local
  issuerRef:
    name: vault-issuer
