apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: vault
spec:
  vault:
    path: pki/sign/akchristiansen-com
    server: https://pi-vault.akchristiansen.com:8200
    auth:
      appRole:
        path: approle
        roleId: "e2aeaf75-2736-b65c-3b8c-f01a22fed41c"
        secretRef:
          name: pi-vault-approle
          key: secretId
