---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: cloudnative-pg
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  postgresGID: 26
  postgresUID: 26
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  storage:
    size: 100Gi
    storageClass: "iscsi-csi"
  superuserSecret:
    name: cloudnative-pg-secret
  bootstrap:
    recovery:
      source: postgres-v16
  postgresql:
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 10GB
      shared_buffers: 512MB
  resources:
    limits:
      memory: 4Gi
  monitoring:
    enablePodMonitor: false
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgres-backups/
      endpointURL: https://nas-1.akchristiansen.com:9000
      serverName: postgres-v16.1-17
      endpointCA:
        name: cloudnative-pg-secret
        key: ca-bundle
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: minio-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: minio-key
  externalClusters:
    - name: postgres-v16
      barmanObjectStore:
        wal:
          compression: bzip2
          maxParallel: 8
        destinationPath: s3://postgres-backups/
        endpointURL: https://nas-1.akchristiansen.com:9000
        endpointCA:
          name: cloudnative-pg-secret
          key: ca-bundle
        s3Credentials:
          accessKeyId:
            name: cloudnative-pg-secret
            key: minio-id
          secretAccessKey:
            name: cloudnative-pg-secret
            key: minio-key
