apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-1
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - vers=4.1
  nfs:
    path: /mnt/primary-pool/K8s/nfs/postgres-1
    server: 10.0.3.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-2
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - vers=4.1
  nfs:
    path: /mnt/primary-pool/K8s/nfs/postgres-2
    server: 10.0.3.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-3
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - vers=4.1
  nfs:
    path: /mnt/primary-pool/K8s/nfs/postgres-3
    server: 10.0.3.2