apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-csi-snapshot-controller
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/csi/snapshot-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: snapshot-controller
      namespace: csi
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-csi-secrets
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/csi/secrets
  prune: true
  dependsOn:
  - name: cluster-apps-security-external-secrets-stores
  sourceRef:
    kind: GitRepository
    name: github
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-csi-iscsi
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/csi/iscsi
  prune: true
  dependsOn:
  - name: cluster-apps-storage-csi-snapshot-controller
  - name: cluster-apps-storage-csi-secrets
  - name: flux-variables
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: iscsi
      namespace: csi
  postBuild:
    substituteFrom:
      - kind: Secret
        name: ca-bundle
        optional: false
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-csi-nfs
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/csi/nfs
  prune: true
  dependsOn:
  - name: cluster-apps-storage-csi-snapshot-controller
  - name: cluster-apps-storage-csi-secrets
  - name: flux-variables
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nfs
      namespace: csi
  postBuild:
    substituteFrom:
      - kind: Secret
        name: ca-bundle
        optional: false
  interval: 30m
  retryInterval: 1m
  timeout: 3m