---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-utilities-nvidia-device-plugin
  namespace: flux-system
spec:
  path: ./cluster/apps/utilities/nvidia-device-plugin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: nvidia-device-plugin
      namespace: nvidia-device-plugin
  interval: 30m
  retryInterval: 1m
  timeout: 3m
