---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bungeecord
  namespace: minecraft
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      main:
        containers:
          main:
            image:
              repository: itzg/bungeecord
              tag: latest
              pullPolicy: IfNotPresent
            env:
              UID: 1000
              TZ: America/Anchorage
              BUNGEE_JAR_FILE: "/server/server.jar"
              TYPE: CUSTOM
              MEMORY: 512M
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 25577
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 20
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                memory: 600Mi
            securityContext:
              runAsUser: 1000
        initContainers:
          chown-sidercar:
            image:
              repository: busybox
              tag: latest
              pullPolicy: IfNotPresent
            command: ["sh", "-c", "chown -R 1000:1000 /server"]
            securityContext:
              runAsUser: 0
    service:
      main:
        enabled: false
        primary: false
        ports:
          http:
            port: 0
            enabled: false
      lb:
        enabled: true
        primary: true
        type: LoadBalancer
        controller: main
        annotations:
          io.cilium/lb-ipam-ips: 10.0.0.7
          external-dns.alpha.kubernetes.io/hostname: mc.gageserver.com
        ports:
          http:
            enabled: false
            port: 80
            primary: false
          mc-br-lb:
            enabled: true
            port: 19132
            primary: false
            protocol: UDP
            targetPort: 19132
          mc-lb:
            enabled: true
            port: 25565
            primary: true
            protocol: TCP
            targetPort: 25577
    persistence:
      bungeecord-data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: bungeecord-data
        globalMounts:
          - path: /server
            readOnly: false
