apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ingress-issuer-approle
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: ingress-issuer-approle
  data:
  - secretKey: secretId
    remoteRef:
      key: issuer-secrets
      property: ingress-issuer-secretid