apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: yatai-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  data:
    - secretKey: postgres-secret
      remoteRef:
        key: yatai-secrets
        property: postgres-secret
