apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-secret
  namespace: yatai-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: s3-secret
  data:
    - secretKey: access_key
      remoteRef:
        key: yatai-secrets
        property: access_key
    - secretKey: secret_key
      remoteRef:
        key: yatai-secrets
        property: secret_key
