---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-istio-system-gateways-certificate
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/istio-system/gateways/certificate
  dependsOn:
    - name: cluster-apps-security-cert-manager
    - name: cluster-apps-networking-istio-system-issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-istio-system-gateways-internal
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/istio-system/gateways/internal
  dependsOn:
    - name: cluster-apps-networking-istio-system-istiod
    - name: cluster-apps-networking-istio-system-gateways-certificate
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-istio-system-gateways-external
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/istio-system/gateways/external
  dependsOn:
    - name: cluster-apps-networking-istio-system-istiod
    - name: cluster-apps-networking-istio-system-gateways-certificate
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true
