---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: creative
  namespace: minecraft
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      main:
        containers:
          main:
            image:
              repository: itzg/minecraft-server
              tag: java17-graalvm-ce
              pullPolicy: IfNotPresent
            envFrom: 
              - secret: atm9-secret
            env:
              UID: 1000
              TZ: America/Anchorage
              EULA: TRUE
              EXEC_DIRECTLY: TRUE
              MOD_PLATFORM: AUTO_CURSEFORGE
              CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9
              MEMORY: 10G
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - mc-health
                  initialDelaySeconds: 60
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 20
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 2
                memory: 12G
              limits:
                cpu: 6
                memory: 12G
            securityContext:
              runAsUser: 1000
        initContainers:
          chown-sidercar:
            image:
              repository: busybox
              tag: latest
              pullPolicy: IfNotPresent
            command: ["sh", "-c", "chown -R 1000:1000 /data"]
            securityContext:
              runAsUser: 0
    service:
      main:
        enabled: false
        primary: false
        ports:
          http:
            port: 0
            enabled: false
      lb:
        enabled: true
        primary: true
        type: LoadBalancer
        controller: main
        annotations:
          io.cilium/lb-ipam-ips: 10.0.0.8
        ports:
          http:
            enabled: false
            port: 80
            primary: false
          mc-lb:
            enabled: true
            port: 25566
            primary: true
            protocol: TCP
            targetPort: 25565
    persistence:
      atm9-data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: iscsi-csi
        retain: true
        size: 50Gi
        globalMounts:
          - path: /data
            readOnly: false
          - path: /downloads
            readOnly: false