---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atm9-secret
  namespace: minecraft
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: atm9-secret
  data:
    - secretKey: CF_API_KEY
      remoteRef:
        key: atm9
        property: CF_API_KEY