apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bungeecord/ks.yaml
  - ./creative/ks.yaml
  # - ./hardcore/ks.yaml
  - ./lobby/ks.yaml
  # - ./survival/ks.yaml
  # - ./uhc/ks.yaml
  - ./namespace.yaml
