---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
  labels:
    istio-injection: disabled
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: baseline
