apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: meshconfig-cacertificates-pem
  namespace: istio-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: meshconfig-cacertificates-pem
  data:
    - secretKey: pem
      remoteRef:
        key: issuer-secrets
        property: meshconfig-cacertificates-pem
