---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subnet-router
  namespace: headscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: subnet-router
  namespace: headscale
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resourceNames: ["subnet-router-0", "subnet-router-1", "subnet-router-2"]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: subnet-router
  namespace: headscale
subjects:
- kind: ServiceAccount
  name: "subnet-router"
  namespace: headscale
roleRef:
  kind: Role
  name: subnet-router
  namespace: headscale
  apiGroup: rbac.authorization.k8s.io
