---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: subnet-router
  namespace: headscale
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resourceNames: ["subnet-router-state"]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: subnet-router
  namespace: headscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: subnet-router
subjects:
  - kind: ServiceAccount
    name: subnet-router
    namespace: headscale
