---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headscale-preauthkey
  namespace: headscale
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: headscale-preauthkey
    template:
      engineVersion: v2
      data:
        TS_AUTHKEY: "{{ .preauthkey }}"
  dataFrom:
    - extract:
        key: headscale-secrets