---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: subnet-router-secret
  namespace: headscale
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: subnet-router-secret
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: headscale-secrets
        property: subnet-router-authkey
