---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-global-egress"
spec:
  endpointSelector:
    matchLabels:
      {}
  egress:
    - toEntities:
        - all
