---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-monitoring-metrics-server
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/monitoring/metrics-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true