---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 4.5.12
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    nextcloud:
      host: cloud.akchristiansen.com
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
      defaultConfigs:
        redis.config.php: false
        apcu.config.php: false
        smtp.config.php: false
      configs:
        redis.config.php: |-
          <?php
          $CONFIG = array (
            'memcache.local' => '\OC\Memcache\APCu',
            'memcache.distributed' => '\OC\Memcache\Redis',
            'memcache.locking' => '\OC\Memcache\Redis',
            'redis' => array(
              'host' => 'redis-master.redis.svc.cluster.local',
              'port' => '6379'
            )
          );
        logging.config.php: |-
          <?php
          $CONFIG = array (
            'log_type' => 'file',
            'logfile' => 'nextcloud.log',
            'loglevel' => 0,
            'logdateformat' => 'F d, Y H:i:s'
            );
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'overwritehost'     => 'cloud.akchristiansen.com',
            'overwriteprotocol' => 'https',
          );
    persistence:
      enabled: true
      existingClaim: nextcloud
    cronjob:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgres-rw.cloudnative-pg.svc.cluster.local
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: db-username
        passwordKey: db-password
    resources:
      limits:
        cpu: 1
        memory: 2000Mi
      requests:
        cpu: 100m
        memory: 200Mi
    hpa:
      enabled: true
      cputhreshold: 60
      minPods: 2
      maxPods: 6
    livenessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
