apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - nolock
    - vers=3
    - async
  nfs:
    path: /mnt/primary-pool/Nextcloud
    server: 10.0.6.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  storageClassName: ""
  volumeName: nextcloud
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
