---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: nextcloud-secrets
  data:
    - secretKey: nextcloud-username
      remoteRef:
        key: nextcloud-secrets
        property: nextcloud-username
    - secretKey: nextcloud-password
      remoteRef:
        key: nextcloud-secrets
        property: nextcloud-password
    - secretKey: db-username
      remoteRef:
        key: nextcloud-secrets
        property: db-username
    - secretKey: db-password
      remoteRef:
        key: nextcloud-secrets
        property: db-password
