---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-security-kubelet-csr-approver
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/security/kubelet-csr-approver/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  wait: true
