---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: sops-encrypted
    namespace: flux-system
spec:
    interval: 5m
    path: ./cluster/flux-system
    prune: false
    sourceRef:
        kind: GitRepository
        name: gitops
    decryption:
        provider: sops
        secretRef:
            name: sops-age
resources:
- gotk-components.yaml
- gotk-sync.yaml
- gotk-decryption.yaml
- ./helm-charts/kustomization.yaml