apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - "BlockVolume"
        - "Passt"
        - "HypervStrictCheck"
        - "CPUManager"
        - "CPUNodeDiscovery"
