---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubevirt
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.0.0/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.0.0/kubevirt-cr.yaml
patchesStrategicMerge:
  - ./namespace.yaml
  - ./kubevirt.yaml
labels:
  - pairs:
      app.kubernetes.io/name: kubevirt
      app.kubernetes.io/instance: kubevirt
      app.kubernetes.io/part-of: kubevirt
