---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-security-vault
  namespace: flux-system
spec:
  path: ./cluster/apps/security/vault/app
  dependsOn:
    - name: cluster-apps-security-cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-git-repo
  decryption:
    provider: sops
    secretRef:
      name: sops-vault-key
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vault
      namespace: vault
  interval: 30m
  retryInterval: 1m
  timeout: 5m