---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-utilities-spegel
  namespace: flux-system
spec:
  path: ./cluster/apps/utilities/spegel/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: spegel
      namespace: spegel
  interval: 30m
  retryInterval: 1m
  timeout: 5m
