apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-tailscale-secret
  namespace: istio-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: k8s-tailscale-secret
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: headscale-secrets
        property: k8s-authkey
