---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    meta.helm.sh/release-name: cert-manager
    meta.helm.sh/release-namespace: cert-manager
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.14.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    installCRDs: true
    enableCertificateOwnerRef: true
    featureGates: "ExperimentalGatewayAPISupport=true,ExperimentalCertificateSigningRequestControllers=true"
    extraArgs:
      - "--dns01-recursive-nameservers=1.1.1.1:53"
    replicaCount: 3
    podDisruptionBudget:
      enabled: true
    webhook:
      replicaCount: 3
      podDisruptionBudget:
        enabled: true
