---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 18.16.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: standalone
    auth:
      enabled: false
      sentinel: false
    master:
      persistence:
        storageClass: "iscsi-csi"
        size: 50Gi
