---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: immich-server
  values:
    defaultPodOptions:
      runtimeClassName: nvidia
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: immich-machine-learning
    controllers:
      main:
        replicas: 2
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.98.2
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            resources:
              requests:
                memory: 250Mi
    service:
      main:
        ports:
          http:
            port: 3003
    persistence:
      library:
        type: persistentVolumeClaim
        existingClaim: immich
        globalMounts:
          - path: /usr/src/app/upload
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache