apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-env-configuration
  namespace: minio-tenant
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: k8s-env-configuration
  data:
    - secretKey: config.env
      remoteRef:
        key: minio-secrets
        property: k8s-env-configuration
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-kes-configuration
  namespace: minio-tenant
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: k8s-kes-configuration
  data:
    - secretKey: server-config.yaml
      remoteRef:
        key: minio-secrets
        property: k8s-kes-configuration
