apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: headscale-gateway
  namespace: headscale
  annotations:
    io.cilium/lb-ipam-ips: 10.0.0.10
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      hostname: headscale-ui.akchristiansen.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: tls-secrets
      allowedRoutes:
        namespaces:
          from: Same
    - name: http
      hostname: headscale-ui.akchristiansen.com
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: https
  namespace: headscale
spec:
  parentRefs:
    - name: headscale-gateway
      sectionName: https
  hostnames: ["headscale-ui.akchristiansen.com"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: headscale-ui
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
  namespace: headscale
spec:
  parentRefs:
    - name: headscale-gateway
      sectionName: http
  hostnames: ["headscale-ui.akchristiansen.com"]
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
