---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headscale-config
  namespace: headscale
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: headscale-config
    template:
      engineVersion: v2
      data:
        config.yaml: |
          ---
          server_url: https://headscale.akchristiansen.com

          listen_addr: 0.0.0.0:8080
          metrics_listen_addr: 0.0.0.0:9090
          grpc_listen_addr: 0.0.0.0:50443

          grpc_allow_insecure: false

          noise:
            private_key_path: /etc/headscale/noise_private.key

          prefixes:
            v4: 100.64.0.0/10

          derp:
            server:
              enabled: false
              region_id: 999
              region_code: "akchristiansen_network"
              region_name: "AKChristiansen Network"
              stun_listen_addr: "0.0.0.0:3478"
              private_key_path: /etc/headscale/derp_server_private.key
              automatically_add_embedded_derp_region: true
              ipv4: 1.2.3.4
            urls:
              - https://controlplane.tailscale.com/derpmap/default
            paths: []
            auto_update_enabled: true
            update_frequency: 24h

          disable_check_updates: false
          ephemeral_node_inactivity_timeout: 30m
          node_update_check_interval: 10s

          database:
            type: sqlite
            sqlite:
              path: /etc/headscale/db.sqlite

          log:
            format: text
            level: info

          acl_policy_path: ""

          dns_config:
            base_domain: akchristiansen.com
            override_local_dns: true
            magic_dns: false
            nameservers:
              - 94.140.14.14
              - 94.140.15.15
            restricted_nameservers:
              akchristiansen.com:
                - 10.0.6.1
            domains:
              - akchristiansen.com

          unix_socket: /tmp/headscale.sock
          unix_socket_permission: "0770"

          oidc:
            only_start_if_oidc_is_available: true
            issuer: "{{ .issuer }}"
            client_id: "{{ .client_id }}"
            client_secret: "{{ .client_secret }}"
            expiry: 180d
            use_expiry_from_token: false
            scope: ["openid", "profile", "email"]

          logtail:
            enabled: false

          randomize_client_port: false
  dataFrom:
    - extract:
        key: headscale-secrets