---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headscale
  namespace: headscale
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/juanfont/headscale
              tag: 0.22.3
              pullPolicy: IfNotPresent
            env:
              PUID: 1000
              PGID: 1000
              TZ: America/Anchorage
            args: ["headscale", "serve"]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8080
                  initialDelaySeconds: 10
                  periodSeconds: 2
                  timeoutSeconds: 1
                  failureThreshold: 20
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                cpu: 1
                memory: 1000Mi
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: true
            port: 8080
          metrics:
            enabled: true
            port: 9090
            protocol: TCP
          grpc:
            enabled: true
            port: 50443
            protocol: TCP
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: nfs-csi
        accessMode: ReadWriteOnce
        retain: true
        size: 5Gi
        globalMounts:
          - path: /etc/headscale
            readOnly: false
      secrets:
        type: secret
        name: headscale-secrets
        advancedMounts:
          main:
            main:
              - path: /etc/headscale/config.yaml
                readOnly: true
                subPath: config.yaml
              - path: /etc/headscale/acl.yaml
                readOnly: true
                subPath: acl.yaml
