---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-world-to-headscale"
  namespace: headscale
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: headscale
  ingress:
    - fromEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "3478"
              protocol: UDP
