---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headscale-config
  namespace: headscale
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: headscale-config
  data:
    - secretKey: config.yaml
      remoteRef:
        key: headscale-config
        property: config.yaml
    - secretKey: acl.yaml
      remoteRef:
        key: headscale-config
        property: acl.yaml
