apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headscale-cert
  namespace: headscale
spec:
  secretName: tls-secrets
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: headscale.akchristiansen.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - headscale.akchristiansen.com
  issuerRef:
    name: ingress-issuer
    kind: ClusterIssuer
