---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-gaming-ark
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-storage-nfs-csi
  path: ./cluster/apps/gaming/ark/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  # healthChecks:
  #   - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #     kind: HelmRelease
  #     name: ark
  #     namespace: ark
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
        optional: false
