apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-secrets
  namespace: mariadb
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: mariadb-secrets
  data:
  - secretKey: mariadb-root-password
    remoteRef:
      key: mariadb-secrets
      property: mariadb-root-password
  - secretKey: mariadb-replication-password
    remoteRef:
      key: mariadb-secrets
      property: mariadb-replication-password
  - secretKey: mariadb-password
    remoteRef:
      key: mariadb-secrets
      property: mariadb-password