---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-media-immich
  namespace: flux-system
spec:
  path: ./cluster/apps/media/immich/app
  dependsOn:
    - name: cluster-apps-networking-istio-system-istiod
    - name: cluster-apps-storage-csi-nfs
    - name: cluster-apps-database-cloudnative-pg-cluster
    - name: cluster-apps-security-external-secrets-stores
    - name: cluster-apps-database-redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: immich-server
      namespace: immich
    - apiVersion: apps/v1
      kind: Deployment
      name: immich-microservices
      namespace: immich
    - apiVersion: apps/v1
      kind: Deployment
      name: immich-machine-learning
      namespace: immich
  interval: 30m
  retryInterval: 1m
  timeout: 5m
