---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-istio-system-cni
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/networking/istio-system/cni/app
  dependsOn:
    - name: cluster-apps-networking-istio-system-base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-git-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cni
      namespace: istio-system
  wait: true