---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-k10
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/k10/app
  prune: true
  dependsOn:
    - name: cluster-apps-security-external-secrets-stores
    - name: cluster-apps-storage-csi-iscsi
    - name: cluster-apps-storage-csi-nfs
    - name: flux-variables
  sourceRef:
    kind: GitRepository
    name: github
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: k10
      namespace: kasten-io
  interval: 5m
  retryInterval: 10m
  timeout: 20m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: ca-bundle
        optional: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-k10-config
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/k10/config
  prune: true
  dependsOn:
    - name: cluster-apps-storage-k10
  sourceRef:
    kind: GitRepository
    name: github
  interval: 5m
  retryInterval: 10m
  timeout: 20m
