apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |-
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    akchristiansen.com:53 {
        hosts {
            10.0.0.3 vault.akchristiansen.com
            10.0.0.4 auth.akchristiansen.com
            10.0.0.5 unifi.akchristiansen.com
            10.0.0.6 minio-api.akchristiansen.com
            10.0.0.7 mc.gageserver.com
            10.0.0.8 k10.akchristiansen.com
            10.0.0.9 headscale.akchristiansen.com
            10.0.0.10 headscale-ui.akchristiansen.com
            ttl 3600
            reload 0
            no_reverse
            fallthrough akchristiansen.com
        }
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
